### ISSUE TITLE
GHC Version Diff

### ISSUE THREAD

**Issue by eborden** [freckle/rcl#12]
RCL provides information about packages changes, but it does not provide feedback on GHC version changes. These only happen in major LTS updates, but calling them out with the tool makes it clearer and more visible.

Not much needs to be done beyond:
1. Provide the previous version and the new version.
1. Link to the release notes of the latest version (maybe versions between?)

**Comment by pbrisbin** [comment]
[When we load `/snapshots`](https://github.com/freckle/rcl/blob/main/src/Rcl/Resolver.hs#L86), we're currently discarding the description details. We can grab that and parse it for the compiler:

![](https://files.pbrisbin.com/screenshots/screenshot.3382277.png)

There doesn't seem to be any markdown CHANGELOG floating anywhere that we could run our existing parser over. So, yeah, I think if we detect a GHC change, we just link to the release notes for the newer version. I don't think we need to take on the complexity of working out the versions in between, but... patches welcome.
